name: GitHub Actions Demo
on: [push]    #we want that the when the push event happen trigger the workflow
jobs:
  my-firs-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3       # we use this becasue some of the files are locally like requirement.txt and workflows not fint it so we use this it clone the files of the repo in the action
      - name: hello
        run: |
          echo "Hello world"
      - name : run python script
        run: |
          pip install -r requirements.txt
          pythonci.py

     

